#!/bin/sh

lb config noauto \
	--apt-recommends false \
	--architecture i386 \
	--binary-indices false \
	--binary-images usb-hdd \
	--bootappend-live "ip=frommedia nolocales nouser username=root quickreboot" \
	--distribution squeeze \
	--hostname opal \
	--linux-flavours 686 \
	--memtest none \
	--syslinux-timeout 5 \
	"$@"
