#!/bin/sh

lh config noautoconfig \
	--apt-recommends false \
	--architecture i386 \
	--binary-indices false \
	--binary-images usb-hdd \
	--bootappend-live "ip=frommedia console=tty0 console=ttyS0,9600n8 live-getty nolocales quickreboot" \
	--distribution lenny \
	--linux-flavours 486 \
	--memtest none \
	--syslinux-timeout 5 \
	"$@"
