#!/bin/sh

lb config noauto \
	--apt-indices false \
	--apt-recommends false \
	--architecture i386 \
	--binary-images hdd \
	--bootappend-live "boot=live config ip=frommedia console=ttyS0,38400n8 nouser hostname=pebble username=root quickreboot" \
	--distribution squeeze \
	--firmware false \
	--linux-flavours 486 \
	--memtest none \
	"${@}"
