#!/bin/sh

lh config noautoconfig \
	--binary-images usb-hdd \
	--distribution lenny \
	--bootappend-live "ip=frommedia console=tty0 console=ttyS0,9600n8 live-getty quickreboot" \
	--syslinux-timeout 5 \
	"$@"
