#!/bin/sh

screen -t host1 \
kvm --hda binary.img --nographic \
    --net nic,macaddr=52:54:00:12:34:56,vlan=0 \
    --net user,vlan=0 \
    --net nic,macaddr=52:54:00:12:34:57,vlan=1 \
    --net socket,listen=127.0.0.1:1234,vlan=1

echo Hit enter once the first host is up
read answer

screen -t host2 \
kvm --hda binary.img --nographic \
    --net nic,macaddr=52:54:00:12:35:56,vlan=2 \
    --net socket,connect=127.0.0.1:1234,vlan=2
